feat: конфигурационные настройки и реализация Users и Categories
Sasha1239/java-explore-with-me pull request #1
Opened 2022-11-13 13:02 UTC by Sasha1239

2022-11-20 22:55 UTC, alexache requested changes

2022-11-20 22:55 UTC, alexache commented on docker-compose.yml
> +      - ewm-db
Он еще зависит и от сервиса статистики

2022-11-20 22:55 UTC, alexache commented on main/pom.xml
> +            <version>5.0.0</version>
Версии должны быть указаны через dependencyManagement у родительского модуля

2022-11-20 22:55 UTC, alexache commented on main/pom.xml
> +                <version>1.1.3</version>
Тоже касается и плагинов - версию можно задать через pluginManagement в родительском модуле

2022-11-20 22:55 UTC, alexache commented on statistic/src/main/java/ru/practicum/dto/EndpointHitMapper.java
> +    public ViewStatisticDto toViewStatisticDto(EndpointHit endpointHit) {
Разве не получилось бы обойтись статическими методами, чтобы не требовался объект маппера?

2022-11-20 22:55 UTC, alexache commented on statistic/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +    private String app;
У полей можно было бы добавить валидаций

2022-11-20 22:55 UTC, alexache commented on statistic/src/main/java/ru/practicum/model/EndpointHit.java
> +@Data
У моделей JPA не должно быть такой аннотации, как и @EqualsAndHashcode, тема корректного написания equals для моделей немного сложнее

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/categories/controller/CategoryController.java
> +@Validated
Это можно пропустить при @RestController, Spring Boot и @Valid в методах

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/categories/dto/CategoryMapper.java
> +    public CategoryDto toCategoryDto(Category category) {
Тут вопрос - почему бы не обойтись простыми статическими методами?

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/categories/model/Category.java
> +@Data
@Data не должны использоваться на моделях JPA

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/compilations/model/Compilation.java
> +@Data
Повторный комментарий про @Data

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/events/model/Event.java
> +@Data
Повторный комментарий

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/events/model/Event.java
> +    List<User> participantList = new ArrayList<>();
Не хватает модификатора доступа

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Не очень хороший способ подсчитывать это вручную на поле, можно начать получать проблемы при одновременной работе с одним и тем же событием

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        BooleanBuilder builder = new BooleanBuilder();
Не вижу, где используются разные виды сортировок

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/events/controller/EventController.java
> +        return eventService.getAllPublicEvents(text, categories, paid,
По ТЗ: "Каждый публичный запрос для получения списка событий или полной информации о мероприятии должен фиксироваться сервисом статистики." - в данном методе не вижу использования сервиса статистики

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/events/model/Event.java
> +    private int confirmedRequests;
действительно ли нужно хранить это в таблице?

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/requests/model/Request.java
> +@Data
Повторный комментарий

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/users/model/User.java
> +@Data
Повторный коммент

2022-11-20 22:55 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        increaseConfirmedRequestsPrivate(event);
Кроме жтой части метод работает хорошо, только я немного запутался, когда его искал, почему он не в RequestController/RequestServiceImpl?

2022-11-21 17:26 UTC, Sasha1239 commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        increaseConfirmedRequestsPrivate(event);
Я увидел его в событиях, решил сделать в событиях

2022-11-24 11:59 UTC, alexache requested changes

2022-11-24 11:59 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +                    events.stream().sorted(Comparator.comparing(Event::getEventDate).reversed());
stream().sorted() не меняет список events, раз нет вызова коллектора, так что это просто бесполезные вызовы. К тому же, если делать сортировку по результатам пагинации, то и сортировка будет только в рамках данной страницы, что не есть требуемое поведение

2022-11-24 11:59 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +                    events.stream().sorted(Comparator.comparing(Event::getViews).reversed());
Я так и не нашел, где выставляются эти views на объекте события. Если я ничего не пропустил, то этого и не происходит. getHits() нигде не вызывается, это точно нужно исправлять

2022-11-24 11:59 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Этот комментарий еще остается в силе. Такой способ не будет полноценно работать, когда бует больше чем 1 сервис. К тому же это свойство вообще лишнее и может быть получено простым запросом к таблице существующих заявок на мероприятие

2022-11-26 09:31 UTC, alexache requested changes

2022-11-26 09:31 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events.forEach(event -> {
По API сервиса статистики можно запрашивать количество просмотров по списку событий одним запросом. То есть можно получить от сервиса связку события на количество его просмотров

2022-11-26 09:31 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        if (event.getParticipantLimit() == event.getConfirmedRequests()) {
event.getConfirmedRequests() остался, но его значение теперь нигде не меняется? Это значение можно подсчитывать с помощью селекта по requestRepository  по eventId и Status.CONFIRMED. В случае запроса списка ивентов это значение тоже лучше получать по спискеу событий (допустим через словарь), а потом собирать финальный ответ с распределением знккачения по событиям

2022-11-26 09:31 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        setViews(events);
Это правильный подход, все ок

2022-11-27 12:15 UTC, alexache requested changes

2022-11-27 12:15 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
>                      event.setViews(views.get(0).getHits());
Почему всегда берется только первый элемент списка? В объекте указано к какому URI относится какое количество просмотров, можно, апример сделать 2 словаря - eventId -> URI, URI -> hits и выставить правильное количество просмотров на объекте события

2022-11-27 12:15 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        event.setConfirmedRequests(requests.size());
Но само событие никуда не сохраняется же? А что в случае cancel?  Я предполагал похожий запрос, но в случае запроса события/списка событий, но, если довести до ума этот вариант (и в расмках одной транзакции), то тоже будет допустимо

2022-11-27 12:15 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        List<Request> requests = requestRepository.findByEvent_IdAndStatus(eventId, Status.CONFIRMED);
Можно бы и просто метод count на такой случай сделать

2022-12-01 22:51 UTC, alexache approved these changes

2022-12-01 22:51 UTC, alexache commented on main/pom.xml
> +                        <version>5.0.0</version>
Версии должны быть в родительском модуле

2022-12-01 22:51 UTC, alexache commented on main/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +        event.setInitiator(UserMapper.fromFullDtoToUser(userService.getAllUsers(new Long[]{userId}, 0, 1)
Это кстати странный код. почему не используется метод получения юзера по айди из самого репозитория юзеров?

2022-12-02 14:14 UTC, merged